version: '3.8'

services:
  nginx:
    build:
      context: .
      dockerfile: nginx.dockerfile
    ports:
      - 80:80
    volumes:
      - ./src:/var/www/html
    depends_on:
      - php
  
  php:
    build:
      context: .
      dockerfile: php.dockerfile
    volumes:
       - ./src:/var/www/html
    depends_on:
      - mysql

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  mysql:
    image: mysql:5.7
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
  
  worker:
    build:
      context: .
      dockerfile: php.dockerfile
    volumes:
       - ./src/cannan:/var/www/html/cannan
    working_dir: /var/www/html/cannan
    depends_on:
      - mysql
      - redis
    entrypoint: ["php", "artisan", "queue:listen"]
    command: ["--tries=3", "--queue=high,USPACE-LowPriority,default,USPACE-SUB", "--verbose"]

volumes:
  mysql_data:
  redis_data:
